TechSpiritSS/Terminal-Portfolio

script.js
Hello @TechSpiritSS !
The script at present does not have an option to exit the script.
However I have done the needful by adding an EXIT option in the "help" or "ls" menu.
Along with this, I have also fixed a typo. "Stating -> Starting"
Please assign the issue raised before a hacktoberfest tag and merge this request.
Thank you so much!
=> Added exit functionality & corrected a small spelling mistake

script.js
In my last fix, I accidently redirected the user to user github repository.
This edit doesn't redirect to your repo anymore. It simply closes the window upon clicking.
If you want me to edit it furthermore. Feel free to ask so. I'll be back with more edits soon.
But please do reply fast.
Sorry for inconvenience. Thanks for considering!
=> Not redirecting to github anymore.

script.js
The previous issue of exiting the function has been fixed hereby. 
The pattern of the UI also matches with the existing UI.
Please merge this fix.
=> Fixed the exit function.

index.html, style.css
=> resolved footer_removed issue on clear command

index.html, script.js, style.css
Reverts TechSpiritSS/Terminal-Portfolio#18
=> Revert "feat: add windows maximize feature"

script.js
Arrow key functionality similar to a terminal. Achieved by having an array which stores all commands and iterating through it.
issue #22
=> Added arrow keys functionality

script.js, style.css
Reverts TechSpiritSS/Terminal-Portfolio#27
=> Revert "Added Cheer command"

CONTRIBUTING.md
I have created a contributing file, so that new comers can refer it.
=>  Added contributing file

script.js
Fixes #38 by @N-Shar-ma
To make the terminal UI behave even more like a terminal, the functionality where on pressing tab after an incomplete command, it autocompletes it, has been added!
https://user-images.githubusercontent.com/68962290/194110713-b6aea4d9-3a46-4898-8a1d-879c20d2bcaf.mp4
=> Added tab autocomplete feature

script.js
Fixes #33 by @ashutoshkrris
I have added new command `blogs` that fetch recent blog posts from the blog feed. The blog feed can be from Medium, Dev.to , Hashnode or any blog URL.
=> Add 'blogs' command to fetch latest blogs

script.js
Added a command to show the list of contributors using the GitHub API.
=> Added command "contributors"

script.js
Fixes #53  by @TechSpiritSS 
added type to exit functionality
added type to exit functionality
=> added type to exit functionality

script.js
- [ x] New feature (non-breaking change which adds a functionality/feature)
- [ x] Refactoring Old Code ( non-breaking change replacing already existing code)
Here I have fixed the buttons for changing the size and to minimize and maximize the screen.
=> Updated Script.js to make buttons working.

index.html
- [x ] Refactoring Old Code ( non-breaking change replacing already existing code)
added id to the red button in html file.
- [ x] I have read the **CONTRIBUTING** guidelines in repository.
- [x ] My pull request has a descriptive title and is attached to an existing issue.
- [x ] I haven't repeated the code and it follows established code style of repository.
- [x ] My branch is up-to-date with upstream branch.
=> Updated index.html to add id to the Red Button.

index.html, script.js
Fixes #40  by @michelle-salt
Fixes issue where the up arrow didn't show the correct history by setting the count to the new length of the array on enter.
=> fixed up arrow history issue #40

script.js
* new command added 
* ipconfig for IP details
Fixes #64 by @subhranshuchoudhury
=> new command "ipconfig"

index.html
Added og tags for looking more elegant while shared on social media
=> Added open graph meta tags

script.js
Convert input to lowercase and remove any extra spaces from beginning and end of input.
Fixes #72  by @stallardjw 
Converts user input to lowercase and trims extra spaces at the beginning and end of the input.
This allows users to input the command without having to match the format exactly and won't throw an error if they include extra spaces at the beginning or end of their input. 
[`Here's my preview`](https://stallardjw.github.io/Terminal-Portfolio/)
=> Fix case sensitivity issue

config.json, index.html, script.js
Fixes #63  by @SadashayKanungo
All the data used in `script.js` has been moved to a new file `config.json`. 
Code in `script.js` and `index.html` has been updated to integrate `config.json`.
This change enables everyone to spin up their own terminal-portfolio without going into the codebase. They just have to replace the data in config file with their own.
The JavaScript code also becomes more elegant with this change.
[Here is my preview](https://sadashaykanungo.github.io/Terminal-Portfolio/)
=> Created Config file for all the data

script.js
=> Added new command "repos" to show your repos

index.html, script.js
Fixes #37 
This PR adds the ability to pull github stats of the user linked in the config for github social 
[`Here's my preview`](https://github.com/coodos/Terminal-Portfolio)
=> feat: added github command and api call

script.js
Fixes #70  by @BiswajitSahoo-tech
I fixed an issue, where on reloading theme choice gets reset. I removed a line of code that caused this.
`setTheme("default");`
This is necessary to fixed because it is essential to save the user preference of theme and set user chosen theme whenever that user visits the site
- [Before reload]
- [After reload]
=> fixed the theme reset issue on reloading

script.js
Fixes #68  by @kuberaspeaking
Emulating  a real terminal, you can now clear the terminal by pressing ctrl+l or ctrl+L
=> Clear terminal on ctrl+l

script.js
Debugged the output of Blogs command. Earlier a new line was being created in the terminal before displaying the blogs.
The issue has been resolved by pre fetching the blogs beforehand, same as the functionality used in repos command.
Fixes #76  by @SadashayKanungo 
[`Here's my preview`](https://sadashaykanungo.github.io/Terminal-Portfolio/)
=> Blogs command output rectified

CONTRIBUTING.md
Fixes #84  by @kuberaspeaking 
Previous CONTRIBUTING.md file was not customized to this project and had a couple of grammatical mistakes. 
This commit solves those issues and makes the contribution guide more helpful for people to contribute to this project.
=> Fixed typos, added customization to CONTRIBUTING.md

script.js
Debugged the output of Github command. Earlier a new line was being created in the terminal before displaying the output.
The issue has been resolved by pre fetching the github stats beforehand, same as the functionality used in repos command.
Fixes #81 by @SadashayKanungo 
- [`Here's my preview`](https://sadashaykanungo.github.io/Terminal-Portfolio/)
=> Github command output rectified

config.json, script.js
Fixes #79  by @AbhishekM2001
- [`Here's my preview`](https://abhishekm2001.github.io/Terminal-Portfolio/)
=> Flag issue

script.js
Fixes #39 
- [x ] Bug/Hot fix (non-breaking change which fixes a bug)
- [ x] Refactoring Old Code ( non-breaking change replacing already existing code)
The Arrow Up key brings back previous commands, but puts the cursor at the beginning. In this PR, I made use of setSelectionRange and delay, to move the cursor to the end.
- [x ] I have read the **CONTRIBUTING** guidelines in the repository.
- [x ] My pull request has a descriptive title and is attached to an existing issue.
- [x ] I haven't repeated the code and it follows the established code style of repository.
- [ x] My branch is up-to-date with upstream branch.
=> Fixed Arrow Up function bug

index.html, script.js, style.css, themes/matrix.css, themes/metalic.css, themes/nature.css
Fixes #45  by @TechSpiritSS 
Implemented a responsive dropdown for themes. The title bar now looks clean and is good to see on  mobile as well.
[`Here's my preview`](https://siddharthsinghvats.github.io/Terminal-Portfolio/)
=> make theme dropdown

style.css, themes/default.css, themes/matrix.css, themes/metalic.css, themes/nature.css, themes/sky.css
Fixes #93  by @siddharthsinghvats 
[Link](https://siddharthsinghvats.github.io/Terminal-Portfolio/)
=> Theme dropdown background sync and animation to close icon

index.html, script.js, style.css
Fixes #62 by @muskanbararia
Typing download command downloads the resume using the drive URL.
[Preview](https://siddharthsinghvats.github.io/Terminal-Portfolio/)
=>  add download resume command

index.html, script.js, scripts/buttons.js, scripts/eventListeners.js, scripts/fetchStats.js, scripts/functions.js, scripts/getDetails.js, scripts/themeSetter.js
Fixes #50  by @TechSpiritSS 
- [ x] Refactoring Old Code ( non-breaking change replacing already existing code)
- [ x] Breaking change (fix or feature that would cause existing functionality to change)
script.js file was too lengthy. This PR breaks down script.js into separate JS files. Each JS file contains a specific type of code. The new JS files are created in a new folder "scripts", and exported. The JS files are imported into the main script.js file, and used as required.
Distributions are:-
buttons.js
eventListeners.js
fetchStats.js
functions.js     -> contains the setup functions
getDetails.js
themeSetter.js
and the main file where functions are called
script.js
This will help in easier code look-ups, fixes and builds.
https://pixel99-eng.github.io/pixel-Terminal-Portfolio/
- [x ] …
=> Divided script file into subfiles

script.js, scripts/functions.js
Used the default Eval function to handle all the calculations
Fixes #34  by @BhagatHarsh
Just addes a simple calculator to the website.
you never know when you need it!
The changes are really minor but you can preview by cloning my fork [here](https://github.com/BhagatHarsh/Terminal-Portfolio)
Here's how it looks.
=> Added Calculator

script.js, scripts/compare.js, scripts/functions.js
Fixes #99
This change now helps the user to find a similar command that can be used, if the user has entered a wrong command.
Currently there are 5 top matching commands shown in this change.
looks like this:
[`Here's my preview`](https://bhagatharsh.github.io/Terminal-Portfolio/)
=> Added Recommendations when wrong command is inputted

scripts/eventListeners.js
Fixes #101 by @BhagatHarsh 
Just had to import the commandList to the eventlisteners file.
- [`Here's my preview`](https://bhagatharsh.github.io/Terminal-Portfolio/)
=> Fixed 'Tab' key autocomplete.

config.json, script.js, scripts/functions.js
Fixes #104 by @khushigarg1 
I added the experience command in a terminal portfolio so whenever the user writes the experience command it will show work experience.
(https://khushigarg1.github.io/Terminal-Portfolio/)
=> added experience section

style.css
Fixed the screen flickering when minimized
Fixes #111  by @TechSpiritSS 
Removed the align-center from body which was causing the flickering.
=> style - fixed flickering when getting minimized

script.js, scripts/eventListeners.js, scripts/functions.js, scripts/history.js
Fixes #106 
So after this change now the user's command history is saved.
only the valid commands are saved and, the 'history' command and invalid commands are not saved.
to not clutter up the screen the history command is capped to atmost 10 past commands, after 10 commands it acts as a queue popping the first command and pushing a new one in.
I have also added so that when the user open's the website the old user's commands can be directly accessed by up arrow.
- [`Here's my preview`](https://bhagatharsh.github.io/Terminal-Portfolio/)
=> Added the History command

scripts/themeSetter.js
Fixes #114 by @harsitagarwalla
- [ x] Refactoring Old Code ( non-breaking change replacing already existing code)
TO minimise the number of lines of old existing codso as to increase the readability and to apply **DRY** principle.
- [ x] I have read the **CONTRIBUTING** guidelines in repository.
- [ x] My pull request has a descriptive title and is attached to an existing issue.
- [x ] I haven't repeated the code and it follows established code style of repository.
- [x ] My branch is up-to-date with upstream branch.
=> Harsitagarwalla187

config.json
Fixes  #117  by @arjun118 
Images are descriptive
---
---
[`try it here`](https://arjun118.github.io/Terminal-Portfolio/)
=> fixed extra text and incorrect heading while trying "experience" feature

.vscode/settings.json, scripts/functions.js
Fixes #105 
displays the command list in sorted order.
- [`Here's my preview`](https://bhagatharsh.github.io./Terminal-Portfolio/)
=> Sorts the command list

config.json, script.js, scripts/functions.js
Reverts TechSpiritSS/Terminal-Portfolio#136
Checking History Command
=> Revert "Skill"

config.json, script.js, scripts/functions.js
Reverts TechSpiritSS/Terminal-Portfolio#139
=> Revert "Revert "Skill""

.editorconfig, CODE_OF_CONDUCT.md, README.md, index.html, scripts/buttons.js, scripts/compare.js, scripts/eventListeners.js, scripts/fetchStats.js, scripts/functions.js, scripts/getDetails.js, scripts/themeSetter.js, style.css, themes/default.css, themes/dracula.css, themes/matrix.css, themes/metalic.css, themes/nature.css, themes/sky.css
Fixes #133 by @Siddhesh-Agarwal
- Added a `.editorconfig` for standard EOF and tab length across the repository
- Reformatted code according to the configuration settings.
- Added a new theme inspired by the [Dracula Theme](https://draculatheme.com/)
=> Added `.editorconfig`, Refactored code and added new theme

scripts/functions.js, scripts/history.js
Fixes #126 
In this PR, I have added the history {id} command.
For ex: If we have a history as follows
then on running the 'history 2' command, it will run 'github' command
https://terminal-portfolio-2i3evsjzw-vaibhav31.vercel.app/
=> added history {id} command

config.js, scripts/fetchStats.js, scripts/functions.js, scripts/getDetails.js
Fixes #138  by @TechSpiritSS 
This issue was caused because of the use of latest ES6 feature `assert`, which is not supported by all the browsers at the moment especially non-chromium based browsers.
I replaced that implementation with the old widely accepted import statement, by making minimum changes required.
It is advised that futures coders don't implement the beta features in the code.
- [https://anuragshukla.xyz/Terminal-Portfolio/](https://anuragshukla.xyz/Terminal-Portfolio/)
=> fixed the page load issue in Firefox Desktop and other browsers.

CNAME, index.html, themes/default.css, themes/dracula.css, themes/galaxy.css, themes/matrix.css, themes/metalic.css, themes/nature.css, themes/sky.css, themes/vibrant.css
**Fixes**  #125 by @TechSpiritSS 
[Preview Link](https://dheerajchhatanidc.github.io/Terminal-Portfolio/)
=> Add 2 new theme to the Terminal Portfolio

config.js, scripts/functions.js
Fixes #143 by @Siddhesh-Agarwal 
Fixes #144 by @Siddhesh-Agarwal 
- Improved speed by Using a pre-sorted list instead of sorting it every time (#143)
- Security improvement: used `Function` instead of `eval` (#144)
- [`Here's my preview`](https://siddhesh-agarwal.github.io/Terminal-Portfolio/)
=> Fixes #143 and #144

scripts/functions.js
Fixes #147  by @theanuragshukla 
The contact method was importing properties from config file incorrectly, leading to breaking the markup generation and wrong link was being populated into page.
I removed the buggy accessing of properties with the correct method.
- [`http://anuragshukla.xyz/Terminal-Portfolio/`](http://anuragshukla.xyz/Terminal-Portfolio/)
=> fixed buggy link and markup generation in contact function

config.js, script.js, scripts/functions.js
Fixes #152  by @khushigarg1 
https://khushigarg1.github.io/Terminal-Portfolio/
=> added reset command

config.js, script.js, scripts/eventListeners.js, scripts/functions.js, scripts/history.js
Fixes #154 
Added typing animation.
Also added typing cmd, using which we can see the status of whether typing animation is on or off, and by presenting flags like --on or --off we can turn it on or off. Also by providing a number, the user can set a custom typing speed in ms.
https://user-images.githubusercontent.com/84830429/212666098-c636146a-278d-41f7-9c2f-d9eef3369758.mp4
https://terminal-portfolio-hrqcu48hz-vaibhav31.vercel.app/
=> Added typing animation and typing cmd

style.css
Fixes #108  by @khushigarg1 
https://khushigarg1.github.io/Terminal-Portfolio/
=> responsive

index.html, script.js, scripts/themeSetter.js, style.css
Fixes #1   by @khushigarg1 
https://khushigarg1.github.io/Terminal-Portfolio/
=> Grouping themes

scripts/functions.js, style.css
=> remover anchor tag

config.js, scripts/functions.js
Fixes #162 
Added "help {cmdName}" command which gives a full description of the respective command.
Also, added full info about every cmd in the config file. Info is an array of strings which will be used while explaining the cmd.
https://terminal-portfolio-7aqw9pphs-vaibhav31.vercel.app/
=> Add 'help {cmdName}'

themes/default.css, themes/dracula.css, themes/galaxy.css, themes/matrix.css, themes/metalic.css, themes/nature.css, themes/sky.css, themes/vibrant.css
Fixed issue #135 .
Added a custom scroll bar to every theme.
Added a custom scroll bar to every theme.
https://vatsalmadhur.github.io/Terminal-Portfolio/
=> Changed all css files for customising scrollbars.

scripts/functions.js
Fixes #173
- I have corrected the wrong orientation with 0 linkedIn connections  when social -d command is given 
- I have changed connections:-, rank:-, rating:- to connections : , rank : , rating **:**
- [Typo of the issue was already corrected by someone before I forked]
https://shubhodaya.github.io/Terminal-Portfolio/
=> <orientation changed, typo fixed>

scripts/functions.js
Preview link: https://mohakgupt.github.io/Terminal-Portfolio/
=> Fix: links don't open in new tabs
